<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link href="css/my-style.css" rel="stylesheet">

    <title>PARCEL BUDDY WEBSITE - <?php echo $view->pageTitle; ?></title>
</head>
<body class="d-flex flex-column h-100">
<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-secondary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">PARCELBUDDY</a>
            <form class="d-flex" action="index.php" method="post" onsubmit="return confirm('Are you sure you want to log out?');">
                <button class="btn btn-outline-danger" type="submit">LOGOUT</button>
            </form>
        </div>
    </nav>
</header>
<!-- Bootstrap core JavaScript and Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-pzjw8Yp5BX5PWlP1Uf/cKzr0q5zSLPp/BEjZR5AjGOgYzp4fQsk2taQRIqHsbgRS" crossorigin="anonymous"></script>
</body>
</html>
